### ISSUE TITLE
Deploy Failed - Invalid Release Name

### ISSUE THREAD

**Issue by frarin** [AgicCloud/Demo.Aks.Performance#10]
![image](https://user-images.githubusercontent.com/98345119/168884915-dd8d8a5f-0b86-4be4-879b-ab7ed2edd903.png)

**Comment by frarin** [comment]
Additional info about the error: 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/98345119/169269741-05079e3d-782a-4f4a-b402-0fff968d4575.png)

**Comment by frarin** [comment]
It seems that it takes the Container Registry name without doing a lowercase operation before setting the login server name.. In my case it was frrinaldRegistry vs frrinaldregistry.azurecr.io

**Comment by frarin** [comment]
I tried with a different appName and with a lowercase version of the container registry name, but I got the same error.

![image](https://user-images.githubusercontent.com/98345119/169270913-3c86286c-3389-4158-8108-6d4c6e3aa91c.png)

**Comment by macel94** [comment]
@frarin we saw your error, it was not about the container registry but for the release name for the HELM chart.
https://github.com/frarin/Demo.Aks.Performance/runs/6505159971?check_suite_focus=true#step:10:22

we now introduced a tolower transformation to correct similar errors.
the real problem was here: https://github.com/frarin/Demo.Aks.Performance/blob/322a19dbd68b0f2e6b6a9f35fa3b30e8296d7f49/.github/workflows/main.yml#L7
