### ISSUE TITLE
No Application displayed

### ISSUE THREAD

**Issue by filippo-cala** [AgicCloud/Demo.Aks.Performance#23]
When I try to connect to my application:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/85103736/170235216-f13e7728-91dc-4381-92c3-e97f56969d75.png">

I deployed on my personal AKS instance and works fine.

**Comment by macel94** [comment]
Hi @filippo-cala 

can we ask you what image are you trying to use?
In our tests we used a static web app(stateless app without any dependency) but here it seems like you're having trouble with your image.
Maybe you're using a version of this one: mcr.microsoft.com/azuredocs/azure-vote-front?
We tried running it locally with the V1 tag without running the backend part of the app and we get the same error because the backend dependency is not there.

In our successful tests we used one of these images:
mcr.microsoft.com/dotnet/samples:aspnetapp
mcr.microsoft.com/azuredocs/aks-helloworld:v1

please retry with one of those and tell us if you get our consistent behaviour.

thank you

**Comment by filippo-cala** [comment]
Hi @MACEL94.
I put this image on my ACR that is the same used for the demo and test:

https://github.com/Azure-Samples/azure-voting-app-redis

I pushed this image on my personal AKS cluster without problems, I point to the same image from GitHub Action.

Customer never test "hello world" application so test more complex application or service it's need it.

Thank you for your support!
